### ISSUE TITLE
new dataset checklist for Machine Learning

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1007]
## User story

>As a submitting author  
>I want to see the guidelines for what to submit as part of my machine learning dataset
>So that I can include all the required data and details

## Acceptance criteria

>Given I am on the guidelines page at GigaDB http://gigadb.org/site/guide
>When I click the dropdown for "Dataset Checklists"
>Then I should see an option for "Machine Learning"

>Given I click the "Machine Learning" link
>When I view the page 
>Then I should see the following

we need to add all expected text and tables here

- Short paragraph of prose to explain what is generally expected, 
- Table listing the "usual" files/Items and their suggested format(s)
- Short paragraph to explain what sample information we expect and if there are any community standards the author should follow
- Table listing the expected Sample attributes to be used, including a column for requirement (required or optional), and the attribute descriptions.

## Dependencies
The CMS needs to be completed before this work can be done.

## Additional Info
This is an example of the required functionality described in #595 which is part of Epic #564 

## CMS Backlog Item Ready Checklist

* [x] Business value is clearly articulated (i.e. the user story is clear)
* [ ] Acceptance criteria are clear and testable
* [ ] Content has been signed off by an appropriate level staff member
* [x] Dependencies are identified 
* [ ] No external dependencies would block this item from being completed

## CMS Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Internal Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] The Content has been copy-edited by a second person
* [ ] The content has been made public
