### ISSUE TITLE
Frictionless data package Epic

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1118]
This is an epic to pull together the tickets related to the Frictionless Data Package work that Raniere did during his intern with us in 2022.

* [ ] #1095 
* [ ] #2163

needed to be able to estimate and to the work (TODO):
* [ ] wireframe for how to represent the user interface for #2163
* [ ] create ticket for bulk manifest creation for already published datasets
* [ ] Make sure custom attributes used in frictionless manifests (eg: related_manuscript ) are formally defined (eg: ontology, cv, purl) so that can be re-used and referred to unambiguously in multiple present and future manifests
