### ISSUE TITLE
Integrate with JBrowse 2

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1197]
## User story

>As a website user
>I want to be able to view genome assemblies and annotations in JBrowse 2
>So that I can navigate genome features more easily

## Additional Info

[https://jbrowse.org/jb2/docs/](https://jbrowse.org/jb2/docs/)

This impact a dozens of datasets which have "JBrowse" or "Genome browser"  as a type of external links.

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
Hi,
I attended a workshop yesterday on JBrowse2, its a genome browser, the updated version of the one we have a few instances of running in various old datasets.

Its been streamlined and can more easily handle multiple genomes from one install and use input files hosted in a remote (to the software) location, the only file that needs to be with the software is the config file telling it where to get the data files from.

There are a few pre-requisites required for it:
- A stable and recent version of node
- Git
- Yarn
The setup (described here https://jbrowse.org/jb2/docs/faq/#setup) also says the server needs to support "byte-range requests (e.g. the Range HTTP header)"

The software does the vast majority of the work on the client side, so the machine we host for it wouldn't need to be very large, and it might be possible/sensible to include it in the same server as the [gigadb.org](http://gigadb.org/) webserver (maybe).

Obviously this is an item for the product backlog and will likely not be done for several months yet, but for now ...

From you/tech team, I would like some assistance with just a quick (literally just 20mins!) glance over the setup documentation https://jbrowse.org/jb2/docs/faq/#setup, particularly those things highlighted above, to let me know if there are any red flags that jump out that would be a major blocker/problem to overcome if we were to choose this solution?

If there is nothing major, then I can get the intial work started on the creation of the relevant track and input data that would eventually be displayed in it, which will take time to do.

Thanks
Chris

**Comment by only1chunts** [comment]
Below is the list of datasets that had Jbrowse1 instances setup on parrot, these are therefore the candidates to be implemented in the JBrowse2 platform:
* [ ] 100240
* [ ] 100441
* [ ] 100606
* [ ] 100589
* [ ] 100619
* [ ] 100622

There are many other candidate datasets that could be implemented eg.
* [ ] 102460

Ideally, the new JBrowse2 installation will be accessible by curators in an admin capacity where we can add new datasets as required. This will require documentation.

**Comment by arthurus36-alt** [comment]
hey, this looks like a cool one. i've messed with genome browsers before, though not jbrowse 2 specifically yet. looks pretty standard for an integration though.

is this still open? i can definitely pick this up. let me know if you want me to scope it out or just dive in.
