### ISSUE TITLE
make it easier to discover appropriate links in dataset admin pages

### ISSUE THREAD

**Issue by YFan0019** [gigascience/gigadb-website#1212]
## User story
(listed in order of priority)
[1] 
>As a curator when I try to add an author to a dataset  
>I want to search for a particular dataset number or author name or author OCRID in the "[Dataset:author](https://beta.gigadb.org/adminDatasetAuthor/create)" function
>So that I can quickly add the author to the dataset 

 - [x] This is covered by ticket #1216

[2]
>As a curator when I try to add a funder to a dataset  
>I want to search for a particular dataset number or funder name  in the "[Dataset:funder](https://beta.gigadb.org/datasetFunder/create)" function
>So that I can quickly add the funder to the dataset 

 - [x] This is covered by ticket #1217

[3]
>As a curator when I try to add a sample to a dataset  
>I want to search for a particular  dataset number or sample ID in the "[Dataset:sample](https://beta.gigadb.org/adminDatasetSample/create)" function
>So that I can quickly add the sample to the dataset

 - [ ] This is covered by ticket #1218
 - [ ] This is covered by ticket #2143

[4]
>As a curator when I try to add a project to a dataset  
>I want to search for a particular  dataset number or project name in the "[Dataset:project](https://beta.gigadb.org/adminDatasetProject/create)" function
>So that I can quickly add the project to the dataset 

 - [ ] This is covered by ticket #1219

[5]
>As a curator when I try to add a relation to a dataset  
>I want to search for a particular dataset number  in the "[Dataset:relation](https://beta.gigadb.org/adminRelation/create)" function
>So that I can quickly add the relation to the dataset 

 - [x] This is covered by ticket #1220

## Acceptance criteria
When all linked tickets have been completed

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)
