### ISSUE TITLE
MUST Create a CNGB dropbox replacement on AWS infrastructure

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1235]
## Epic User story

>As a curator
>I want to be able to have authors to upload datasets files in dropboxes even if CNGB pulls the plug on our server there
>So that I can still continue curating author uploaded files

## user stories to complete

* [x] #1221
* [x]  #1634
* [x] #1769 
* [x] #1394 
* [x] #1395 
* [ ] #1396
~~* [ ] #604~~
* [x] #1782
* [x] #1832
* [x] #1863
* [x] #1864

## Additional Info

Use PureFTP as server software for the new server.
Use same account conventions as currently used in File Upload Wizard.
That way, when we resurect File Upload Wizard, we can easily migrate accounts, as FUW uses PureFTP to manage access to the drop boxes.

Core set of Stories to implements:

* [x] Create temporary user dropboxes on EC2 infrastructure (#1221)
* [x] Authors should upload dataset files to server in the cloud (#1233)
* [x] Give reviewers access to author dropboxes in the temporary cloud server (#1234)
* [x] Move FTP server for file upload to own EC2 server and mount the EFS shared dropbox (#1634)
* [x] Update bastion EC2 instance to mount the EFS filesystem (#1769)

In parallel, now that we have enabled Wasabi as final destination for dataset files, the CNGB dropbox replacement needs to allow the curators to curate the files and move the files to Wasabi eventually, this will be implemented with these stories:
 
* [x] Update bastion user provisioning play to generate AWS credentials files (#1394)
* [x] Update rclone provisioning play to generate config with AWS credential files for users (#1395)
* [ ] Create bastion script to switch to Admin role on Wasabi (#1396) - this is required for curators to be able to delete files in Wasabi dataset bucket. It has not been required so far because developers have been responsible for deleting files when requested by curators.

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by pli888** [comment]
Closing this ticket even though ticket https://github.com/gigascience/gigadb-website/issues/1396 has not been done; all the other work items have been completed.
