### ISSUE TITLE
A11y - Dataset Checklist page

### ISSUE THREAD

**Issue by luistoptal** [gigascience/gigadb-website#1380]
## User story

- heading hyerarchy
- low contrast issues (colored text, colored bg)
- landmark issues: misused / empty sections
- empty cells: I imagine screen readers will skip them, cross check to be sure
- link with "here" label (links label should be meaningful)
- table with legend: there is a legend, make it irrelevant for screen readers by adding adequate labels, or some other solution

https://beta.gigadb.org/site/guidegenomic

## Acceptance criteria

- [ ] Fix heading hierarchy
- [ ] Fix contrast issues
- [ ] Fix landmark issues (no empty / contentless sections)
- [ ] Navigate table with empty cells with screen reader (NVDA, VoiceOver, ...) and fix any issues
- [ ] Links have meaningful labels
- [ ] Tables with legends are accessible

**Comment by luistoptal** [comment]
Duplicate

Virtually all of these issues are solved in #1447
