### ISSUE TITLE
using PIDs for individual files

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1582]
## User story

>As website user
>I want to be able to point to a specific file within a datasets
>So that I can explicitly determine which file I have used from that dataset for my work

## Acceptance criteria

>Given I have performed some research on a data file hosted in GigaDB
>When I come to publish that research
>Then I am able to exactly identify the single file I have used in my research

>Given I have read a paper on GigaDB website
>When I want to cite a specific file used in the paper
>Then I can use an ARK ID of that file to cite that file

## Additional Info

This will be required for the use of 3D image files as embedible objects within GigaByte and GigaScience manuscripts. see work in #2091 

The main reference point will always be the dataset as an entity, but we should enable a facility for any to specify down to the individual file exactly which file they are referring to.
We could mint DOI's through datacite for all files, but I think that is excessive due to the need for a high degree of mandatory metadata, and would therefore complicate matters unessacerily.
Instead I would prefer to use something more light-weight such as [HANDLES ](https://www.handle.net/)or [ARKS](https://arks.org/), my preference would be ARK, [this link](https://arks.org/about/comparing-arks-and-other-identifiers/) explains why.

Moving forwards, adding PIDs to individual files would allow us to then add all the files as metadata objects to the DataCite metadata as "relatedIdentifiers" thus further exposing metadata to a wider indexing and hopefully drive discovery.

Whilst a dataset is a collection of files and metadata all easily referenced by a single DOI, and that DOI includes metadata making the dataset FAIR, what about citing an individual file from within a dataset?

Something else to discuss and consider:
 - Could using ARKs be an alternative to providing DOI's for grey-literature with fewer overheads (i.e. no need for all the metadata required by DOIs)

https://en.wikipedia.org/wiki/Archival_Resource_Key#:~:text=An%20Archival%20Resource%20Key%20

# changes involved

* register `gigadb:` prefix to ark alliance
* come up with a way generate public id for each file
* update file table to add a new `pid` column
* when new file added to database, add each pid as a related identifier of the dataset
* display pid of each file in readme
* display in the file table, in its own column

## Tasks

* [ ] #2220
* [ ] #2221
* [ ] #2222

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)
