### ISSUE TITLE
MUST Move FTP server for file upload to own  EC2 server and mount the EFS shared dropbox

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1634]
# User Story

>As an author
>I want to be able to use FTP to upload my dataset files
>So that I can submit my manuscript when I can't use the web based file uploader

## Acceptance criteria

>Given I have dataset files to upload
>When I connect to the ftp using the connection info I have received by email
>Then I can upload my files

## Additional infos

For security reasons (and performance too), the pure-ftpd container service  must not run on production on the same server as the web server (nor should they run on bastion), it should have its own EC2 instance.

 
### Tasks

* [x] The new EC2 instance for the FTP software will need to mount our EFS's access point `/share/config` in read-only mode.
* [x] The new EC2 instance for the FTP software will need to mount our EFS's access point `/share/dropbox` in read/write mode for storing files uploaded by author
* [x] Docker is to run on this instance.
* [x] We should be ab le to re-use the `aws-instance` module with different parameters to avoid duplication.
* [x] PureFTP is the ftp server to use and need to be run as a container service from the new EC2 instance
~~* [ ] Web EC2 instance needs to mount EFS's access point `/share/config` in read/write mode.~~
~~* [ ] Web EC2 instance needs to have the ftp tools installed in its Dockerfile~~
~~* [ ] We should update GigaDB dropbox code to generate ftp configuration and write to `/share/config`~~
* [x] Update Gitlab pipeline to deploy container images to the FTP EC2 instance
~~* [ ] Update `web app_playbook` to also be usable for configuring the FTP EC2 instance as the configuration instructions should be the same~~

Striked out tasks not directly relevant to this story.

## Other infos:

In web EC2 instance new ftp user account can be created in `/Users/owner/code/gigadb-website/fuw/app/backend/models/FiledropAccount.php` with something like:
```
shell_exec(["bash","-c","/usr/bin/pure-pw useradd uploader-$doi -f /share/config/pure-ftpd/pureftpd.passwd -m -u uploader -d /share/dropbox/uploader/$doi  < /var/private/$doi/uploader_token.txt"]) ;
shell_exec(["bash","-c","/usr/bin/pure-pw useradd downloader-$doi -f /share/config/pure-ftpd/passwd/pureftpd.passwd -m -u downloader -d /share/dersopbox/downloader/$doi  < /var/private/$doi/downloader_token.txt"]) ;
```

Tasks:

**Comment by rija** [comment]
Implemented in PR #1826
