### ISSUE TITLE
post-upload script to include addition of readme file metadata

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1840]
## User story

>As a curator
>I want the file size and md5sum value of the newly generated readme_nnnnnn.txt file added to the database
>So that I dont need to go in search of them and add them manually

## Acceptance criteria

>Given post upload script is being run on a dataset
>And the readme file doesn't exist on the server
>When the post-upload script generates the readme file on the server
>Then the script also calculates the size and md5 value of the readme file 
>And populates those details into GigaDB database for the existing file entry for the readme file

>Given post upload script is being run on  a dataset
>And the readme file already exists on the server
>When the post-upload script regenerates the readme file on the server
>Then the script calculates the new size and new md5 value of the readme file 
>And update GigaDB database with those details for the existing file entry for the readme file

>Given post upload script is being run on  a dataset
>When the post-upload script generate or regenerates the readme file on the server
> then the readme file is written with the format "readme_nnnnnn.txt"

## Additional Info
NB - the normal workflow includes the addition of the readme_nnnnnn.txt file to the database as part of the spreadsheet upload, but sometimes that row gets removed from the spreadsheet, so the last IF statement above is to account for those times.

## tasks

* [x] #1880
* [x] #1881

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
The work left to be done on this ticket is to move the step for database-saving of  the MD5checksum and file size after the generation of the readme file because it was with curators that the readme file will be added to the dataset spreadsheet

**Comment by only1chunts** [comment]
I think the work for this issue is done, co am closing it
