### ISSUE TITLE
script to help check file list matches

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1869]
## User story

>As a curator  
>I want to be able to check the list of files I have in my upload spreadsheet with those in the relevant userbox
>So that I can be sure my file list matches the actual files we have

## Acceptance criteria

>Given I have a dataset spreadsheet with a list of files to ingest in the debase
>And I have the files by the authors for that dataset in a userbox
>When I run the matcher script
>Then files that are in the userbox but not in the spreadsheet should be listed as "In userbox/not in spreadsheet"
>And files that are in the spreadsheet but not in the userbox should bee listed as "Not in userbox/in spreasdsheet"

>Given I have a dataset spreadsheet with a list of files to ingest in the debase
>And I have the files by the authors for that dataset in a userbox
>When I run the matcher script
>then hidden files are included in the comparison

## Tasks:

* [x] #1885
* [x] #1886
* [x] #1887
* [x] #1888
* [x] #1889

## Additional Info
I (with the help of chatGTP) have created a script that will take a list of filenames in a text file and search them against a given server location. 
We could use that to check our Excel list matches 

```

#!/bin/bash
# created by chatGTP by request from C Hunter on 17 May 2024
# It requires an input file listing all the files to search for in plain text with 1 filename per line, it can handle relative paths, so include the relative location of the expected filenames in the file list.

# To run this script:
# ./find_files.sh <path/to/file_list.txt> </path/to/search/directory>

# Check if the correct number of arguments are provided
if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <file_list> <search_directory>"
  exit 1
fi

# Assign command-line arguments to variables
file_list="$1"
search_directory="$2"

# Check if the file_list exists
if [[ ! -f "$file_list" ]]; then
  echo "File list $file_list not found!"
  exit 1
fi

# Check if the search_directory exists
if [[ ! -d "$search_directory" ]]; then
  echo "Search directory $search_directory not found!"
  exit 1
fi

# Initialize counters
found_count=0
not_found_count=0

# Create an associative array to store the files in the list
declare -A files_in_list

# Read the file list line by line and populate the associative array
while IFS= read -r relative_path; do
  files_in_list["$relative_path"]=1
done < "$file_list"

# Search for files in the search directory based on the file list
for relative_path in "${!files_in_list[@]}"; do
  found_files=$(find "$search_directory" -type f -path "$search_directory/$relative_path")

  if [[ -n "$found_files" ]]; then
    echo "Files found for $relative_path:"
    echo "$found_files"
    found_count=$((found_count + 1))
  else
    echo "No files found for $relative_path"
    not_found_count=$((not_found_count + 1))
  fi
done

# Initialize reciprocal search count
reciprocal_count=0

# Perform a reciprocal search to find files in the search directory not listed in the file list
echo
echo "Files in $search_directory not listed in $file_list:"
while IFS= read -r file_path; do
  # Get the relative path by stripping the search directory prefix
  relative_path="${file_path#$search_directory/}"
  if [[ -z "${files_in_list[$relative_path]}" ]]; then
    echo "$relative_path"
    reciprocal_count=$((reciprocal_count + 1))
  fi
done < <(find "$search_directory" -type f)

# Print summary
echo
echo "Summary:"
echo "Files found from the list: $found_count"
echo "Files not found from the list: $not_found_count"
echo "Files in $search_directory not listed in $file_list: $reciprocal_count"


```

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
Tasks here:
* Review that script works (fullfill both acceptance criteria)
* add automated test (bats)
* That it validates shell code guidelines
* Is deployed to bastion server with bastion playbook
* If there is a good one, install a xls2csv on bastion too

**Comment by rija** [comment]
Hi @only1chunts 
could you let us know: 
* the dropbox name and DOI of the dataset files you successfully tried on staging bastion
* the dropbox name and DOI of the dataset files you tried with failure on live bastion

Thanks

**Comment by only1chunts** [comment]
Re: STG server, I used the attached file list to compare to user109 dropbox : NB Github doesn't like the file extension .list so I had to append .txt to get it to upload to github, but in the example code beloe the filename was without the .txt suffix!

```
[chrish@ip-10-99-0-199 user109]$ /home/chrish/find_files.sh
Usage: /home/chrish/find_files.sh <file_list> <search_directory>
[chrish@ip-10-99-0-199 user109]$ /home/chrish/find_files.sh /home/chrish/user109.list .
Files found for user109.md5:
./user109.md5
Files found for just_deployed.txt:
./just_deployed.txt
Files found for multiqc_report.html.tar.gz:
./multiqc_report.html.tar.gz
Files found for sample.json:
./sample.json
Files found for readme.txt:
./readme.txt
Files found for testdir/test.txt:
./testdir/test.txt
Files found for multiqc_report.html:
./multiqc_report.html
Files found for filezilla.log:
./filezilla.log
Files found for checksum.md5:
./checksum.md5

Files in . not listed in /home/chrish/user109.list:

Summary:
Files found from the list: 9
Files not found from the list: 0
Files in . not listed in /home/chrish/user109.list: 0
[chrish@ip-10-99-0-199 user109]$

```
[user109.list.txt](https://github.com/gigascience/gigadb-website/files/15429782/user109.list.txt)


Re: Live bastion - it doesn't matter where you try it, it fails at the point of not knowing what a bash script is!
```
[chrish@ip-10-99-0-199 ~]$ ./find_files.sh
-bash: ./find_files.sh: /bin/bash^M: bad interpreter: No such file or directory
[chrish@ip-10-99-0-199 ~]$
```

**Comment by rija** [comment]
Thanks for the info.
Re the error: that's because the first line is not correct (ChatGPT was wrong there).
The correct way of starting a bash script is with 
```
#!/usr/bin/env bash
```
because the `bash` interpreter is not always in the same location, so we need to use the `env` command (which is conventional to be in always the same location) to look up the bash interpreter wherever it is

**Comment by rija** [comment]
Done in PR #1898
