### ISSUE TITLE
Automate linting to improve quality of PRs and speed up PRs reviews

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#2111]
## User story

>As a developer  
>I want linting of submitted code to be automated
>and to have their reports annotate the PR file diffs  
>So that code quality of PR submissions are automatically assessed without extra work needed

## Acceptance criteria

>Given a file from a PR is in PHP  
>When the PR is created  
>Then linting is run  for this file

>Given a file from a PR is in Javascript  
>When the PR is created  
>Then linting is run for this file

>Given a file from a PR is in Bash  
>When the PR is created  
>Then linting is run for this file

## Additional Info

1) Have a local tool to run linting on a developer environment
2) Have multiple pipeline jobs in the "Conformance and security" stage:
 - "Check PHP"
 - "Check Javascript"
 - "Check Shell script"
 3) Update `CONTRIBUTING.md` with the coding style to adhere to for each of the above languages

Coding style to use:
Coding styles: 
PHP: Use PER for PHP coding style (https://www.php-fig.org/per/coding-style/)
Javascript: Use Airbnb coding style
Shell: Shellcheck

Linters to use:

PHP:
* PHP Code sniffer: https://github.com/marketplace/actions/phpcs-check-with-annotations
* PHP Stan: https://phpstan.org

Javascript:
https://github.com/marketplace/actions/eslint-annotate-from-report-json

Shell:
https://github.com/marketplace/actions/shellcheck

Note: ensure the linters run the check on the changes only.

Note: If linter find non-conformant code, it should the fail the job

Note: The pipeline job should trigger automatically

### Sub-stories:

* [ ] #2361
* [ ] #2362
* [ ] #2363

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
Coding styles: 
PHP: Use PER for PHP coding style (https://www.php-fig.org/per/coding-style/)
Javascript: Use Airbnb coding style
Shell: Shellcheck
