### ISSUE TITLE
Deploy GigaDB on production server using GitLab CI/CD

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#519]
# Requirements

* Deploy with HTTPS
* Access to gigadb.org DNS settings

**Comment by rija** [comment]
current draft, still thinking-aloud work in progress notes for now...

# TODO


* [ ] Centos is discontinued as production supported OS, so needs to be replaced on host
* [ ] Ensure we can always roll back to previous version of releases (including config)
* [ ] cold/warm/hot backup or high availability?
* [ ] Create a live environment configuration for nginx
* [ ] What to do with production public dataset storage?
    * [ ] FUW subsystem can be deployed on CNGB (providing docker can be installed there), but do we want to?
* [ ] Create environment for live environment with terraform
* [ ] Add load balancer to infrastructure
* [ ] Initial configuration of load balancer to point to IP address of current CNGB server
* [ ] Reconfigure gigadb.org DNS record to point an A record to the load balancer
* [ ] Make sure redeploy don't obliterate databases
* [ ] make some acceptance tests that are  more like smoke tests:
    * [ ] There is a status page saying all  infrastructure elements's OK/NOT status
        * [ ] and test they are all OK
    * [ ] Can login as a user
    * [ ] Can login as an admin


# Provisional Draft Plan:

(1) Add a load balancer between gigadb.org and CNGB server
(2) Test that setup
(3) Deploy codebase to AWS using CI/CD
(4) Connect production public dataset storage to auto-deployed codebase without severing connection to CNGB server 
(5) Perform testing
(6) Connect gigadb.org to the AWS deployment by changing load balancer settings
(7) Perform testing
(8) Ensure backups work


# Problems

* There is an interlocking dependency between setting up CI/CD pipeline for production an the storage solutions evaluation work.
*  load balancer egress outside the cloud infrastructure might be costly, so keep it short-lived?

**Comment by rija** [comment]
## Stage 1: Prepare for Continuous Delivery Pipeline to live environment

This stage is to prepare the Gitlab pipeline to spawn an environment for live deployment and for FUW to be used only for assessing the storage providers

1. Merge fuw-cicd branch to develop to enable changes for continuous delivery and FUW
2. Design backup/high availability process for the database and the web site
3. Add feature toggle to enable and disable FUW from Gitlab pipeline's actions
4. Add additional performance monitoring of file transfers in FUW 
5. Create and instantiate a live production environment on AWS and front it with a load balancer
6. Smoke test the infrastructure, the database and load balancer


## Stage 2: Deploy GigaDB and new storage providers (temporarily use FUW for storage providers assessment)

Here we deploy the GigaDB codebase to the live environment on AWS. We will have a web url for on the gigadb.org domain but it's not replacing the web site at gigadb.org yet. However it is sufficient to use the deployed File Upload Wizard to partake in storage provider assessment activities in as close to a live environment as we can.
The steps below will need to be repeated for each provider we assess.


1. Configure a storage provider for FUW and GigaDB
2. Deploy develop to staging (gigadb-staging.gigatools.net) for testing
2. Add to GigaDB DNS a record for pre-live.gigadb.org that points to the load balancer's IP address
3. Deploy develop to pre-live (pre-live.gigadb.org) for final check
4. Use the deployment at pre-live.gigadb.org as part of the storage provider assessment activities

## Stage 3: Deploy a copy of production database to the AWS live environment

This stage is to ensure we can have the production data of GigaDB on the AWS live environment.
It is a one-off operation, but we should make sure the operation is repeatable if needed and that the tools are always available and versioned.

1. Devise process to migrate database data from CNGB Postgresql server to the one on AWS live environment
2. Copy current production database to the database server running in AWS
3. Test backup and restore mechanisms for the database


## Stage 4: Replace the CNGB deployment with the AWS deployment of gigadb.org

By this stage, we have selected the storage provider(s) we want to use. We configure GigaDB and FUW to use it.
We also have our production database populated at this stage.
If the choice of provider incurs additional development work, this is where we do that. By the end, gigadb.org will be serving the new codebase on the new storage providers. FUW will be switched off as we want to launch FUW alongside Submission Wizard (and they still haven't been integrated together at this stage anyway).
if we are using CNGB as a mirror for downloads from China, we test that here too (TODO: specific steps for that)

1. Hide FUW from live deployment as it was only use for storage provider evaluation
2. Configure GigaDB to use the selected storage provider(s)
3. Deploy develop to staging (gigadb-staging.gigatools.net) for testing
4. Deploy develop to pre-live (pre-live.gigadb.org) for final check
5. Test backup/high availability for database, datasets files and website
6. Apply migration strategy if any  
7. Update DNS records to direct www.gigadb.org and gigadb.org to the load balancer

## Stage 5: Test and integrate Submission Wizard and File Upload Wizard

By now, The Gitlab-based continuous delivery pipeline is in use to release features to gigadb.org.
Here we can focus back on Submission Wizard and File Upload Wizard, making sure they work well together 
and they provide value to the users.

1. Merge Submission Wizard branch to ``develop``
2. Deploy develop to staging
3. User testing of integrated workflow of SW and FUW and corresponding app changes
4. Deploy develop to staging
5. User testing of integrated workflow of SW and FUW and corresponding app changes
6. Deploy to live

## Next steps

We need tickets for each steps and a GitHub project to manage their execution.

**Comment by rija** [comment]
this is done
