### ISSUE TITLE
Add a help box/check list for MOST conformance to dataset submission management

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#672]
## User story

>As a curator,
>I want a help text and check list on the admin side of dataset submission
>So that I can assert with confidence that a dataset that uses cHGR is compliant with MOST regulations

## Acceptance criteria

>Given I am managing a dataset submission for a dataset using cHGR material
>When I follow all the steps on the check list associated with that dataset submission
>Then I have confidence I have asserted conformance of the dataset

### TODO

* [ ] List detailed steps and roles involved that leads to legal hosting by GigaDB of dataset with cHGR material

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Code is complete
* [ ] Automated tests related to the changes are implemented and passing
* [ ] All automated test suites are passing locally
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] A Pull Request has been created and review requested
* [ ] Pull Request is reviewed and approved
* [ ] The item has been merged to the develop branch
* [ ] All automated test suites are passing on continuous Integration pipeline and item is ready to release
