### ISSUE TITLE
Enable current admin controller for uploading images to write image to S3 using FlySystem

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#964]
* [x] 1. Show image  if it exist, next to "Image upload" in the dataset update form #976 
* [x] 2. 1st case (no image, - i.e: generic image or empty url/location column): show button "Upload new image" #978 
* [x] 3. 2nd case (image associated with the dataset): show two buttons, "Replace image", "Remove image" #978 
* [x] 4. Configure flysystem for S3
* [x] 5. Refactor Image model class using Yii2's ActiveRecord #978 
* [x] 6. Uploaded files go to S3 (using flysystem)

**Comment by rija** [comment]
Hi @kencho51, @pli888


Below, I reckon,  is a summary of remaining  work to do (step by step) on dataset form. Let me know whether it makes sense or not

(1) Create dataset context

* [ ] Don't display metadata fields by default (use CSS class to control the visibility and set ``display`` selector to none by default)

if file chooser changes to have a file selected (detect using an ``onChange`` event):
 
* [ ] Display metadata fields (create a  javascript function to turn on the visibility of the fields)

(2) Update dataset context: 

if dataset is  associated with custom image, do: 

* [ ] Show "Remove image" button
* [ ] Show metadata fields filled with value related to custom image

```
if ($dataset->image !== null && "no_image.png" !== $dataset->image->location) { // dataset has a custom image
	// show remove image button
	// Write javascript that will set metadata fields visibility on	
}
```


(3) Processing the removal of image

When curator click on "Remove image" button, 
It makes an AJAX call to the  adminController's ``actionUpdate()`` method and change the dataset' image_id to that of the generic image
and it replaces the custom image displayed in the form with the generic image.
That is done with something like:

```
document.querySelector('image_preview').innerHTML = '<div><img src=....  style="..."></div>';
```



I reckon that's a lot for one person given the number of days left in the sprint.
We should share the work.

**Comment by rija** [comment]
forgot one task, but we can do that at the end:
 * [ ] Switch dataset form workflow to AWS S3 flysystem adapter

**Comment by rija** [comment]
Hi @kencho51

Below's the first patch. Copy it into a file and then from your branch run:
```
git apply --ignore-space-change --ignore-whitespace /path/to/the/file.patch 
```

It's the Yii migration that create the official row in image table for the generic image:

```
diff --git a/protected/migrations/schema/m220309_165454_generic_image.php b/protected/migrations/schema/m220309_165454_generic_image.php
new file mode 100644
index 000000000..67caa38c8
--- /dev/null
+++ b/protected/migrations/schema/m220309_165454_generic_image.php
@@ -0,0 +1,22 @@
+<?php
+
+class m220309_165454_generic_image extends CDbMigration
+{
+       public function safeUp()
+       {
+           $this->execute("ALTER TABLE ONLY image ALTER COLUMN license SET DEFAULT 'All rights reserved'");
+           $this->execute("ALTER TABLE ONLY image ALTER COLUMN photographer SET DEFAULT 'n/a'");
+           $this->execute("ALTER TABLE ONLY image ALTER COLUMN source SET DEFAULT 'GigaDB'");
+           $this->insert("image", ['id' => 0, 'location' => 'no_image.png', 'url' =>'https://assets.gigadb-cdn.net/images/datasets/no_image.png']);
+       }
+
+       public function safeDown()
+       {
+               $this->delete("image", ['id=0']);
+               $this->execute("ALTER TABLE ONLY image ALTER COLUMN license DROP DEFAULT");
+               $this->execute("ALTER TABLE ONLY image ALTER COLUMN photographer DROP DEFAULT");
+               $this->execute("ALTER TABLE ONLY image ALTER COLUMN source DROP DEFAULT");
+
+
+       }
+}
\ No newline at end of file

```

**Comment by rija** [comment]
@kencho51,

Here a second patch:

```
diff --git a/protected/views/adminDataset/_form.php b/protected/views/adminDataset/_form.php
index 2e4b5a27f..d6d458f65 100644
--- a/protected/views/adminDataset/_form.php
+++ b/protected/views/adminDataset/_form.php
@@ -30,7 +30,11 @@ $cs->registerCssFile('/css/jquery.tag-editor.css');
     'htmlOptions'=>array(
         'class'=>'form-horizontal',
         'enctype'=>'multipart/form-data'),
-)); ?>
+));
+
+echo $form->hiddenField($model, "image_id");
+
+?>
 <div class="span12 form well">
     <div class="form-horizontal">
         <p class="note">Fields with <span class="required">*</span> are required.</p>
```

It will result in the following snippet to appear when viewing source code of rendered dataset form:

```
<input name="Dataset[image_id]" id="Dataset_image_id" type="hidden" value="212" />
```

I think there should only be one more change needed to get  the image removal working, and that will be a javascript function that sets the value of that hidden input field to 0 (id of the generic image from the first patch).

**Comment by kencho51** [comment]
Hi @rija,

When I try to pass the test locally, I got `DatasetKeywordsTest::testItShouldUpdateKeywordsOnUpdate` and `testItShouldUpdateKeywordsOnCreate1OnManagement` failing.

```
 % docker-compose run --rm test ./vendor/phpunit/phpunit/phpunit --testsuite functional --bootstrap protected/tests/functional_custom_bootstrap.php --verbose --configuration protected/tests/phpunit.xml --no-coverage protected/tests/functional/DatasetKeywordsTest.php
..............
There were 3 failures:

1) DatasetKeywordsTest::testItShouldUpdateKeywordsOnUpdate with data set "no keyword" ('', array())
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'http://gigadb.dev/dataset/100002'
+'http://gigadb.dev/adminDataset/update/id/210'

/var/www/protected/tests/functional/DatasetKeywordsTest.php:45
/var/www/vendor/aik099/phpunit-mink/library/aik099/PHPUnit/BrowserTestCase.php:369
/var/www/vendor/aik099/phpunit-mink/library/aik099/PHPUnit/BrowserTestCase.php:318

2) DatasetKeywordsTest::testItShouldUpdateKeywordsOnUpdate with data set "two clean keywords" ('bam, dam', array('bam', 'dam'))
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'http://gigadb.dev/dataset/100002'
+'http://gigadb.dev/adminDataset/update/id/210'

/var/www/protected/tests/functional/DatasetKeywordsTest.php:45
/var/www/vendor/aik099/phpunit-mink/library/aik099/PHPUnit/BrowserTestCase.php:369
/var/www/vendor/aik099/phpunit-mink/library/aik099/PHPUnit/BrowserTestCase.php:318

3) DatasetKeywordsTest::testItShouldUpdateKeywordsOnUpdate with data set "two keywords and one dodgy" (' am', array('am'))
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'http://gigadb.dev/dataset/100002'
+'http://gigadb.dev/adminDataset/update/id/210'

/var/www/protected/tests/functional/DatasetKeywordsTest.php:45
/var/www/vendor/aik099/phpunit-mink/library/aik099/PHPUnit/BrowserTestCase.php:369
/var/www/vendor/aik099/phpunit-mink/library/aik099/PHPUnit/BrowserTestCase.php:318

ERRORS!
Tests: 6, Assertions: 9, Errors: 3, Failures: 3.
Restoring current database...
ERROR: 2
```

After further look into this error, I think it is because we have replaced the old `images` model, which caused the `actionCreate1()` in DatasetSubmissionController and `datasetSubmission/_form1.php` not working properly. 

It seems not related to the PR #978, but if it is not fixed, the `unit_func_tests` in gitlab would fail. 
So, should this error be fixed this PR?

**Comment by rija** [comment]
that's done
